name: Build Carlinho-Linux ISO

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install live-build (versão atual do Git Debian)
        run: |
          sudo apt-get update
          sudo apt-get install -y git squashfs-tools xorriso debian-archive-keyring debootstrap make gettext po4a
          git clone https://salsa.debian.org/live-team/live-build.git /tmp/live-build
          cd /tmp/live-build
          sudo make install
          lb --version

      - name: Build ISO
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          chmod +x build.sh
          sudo bash ./build.sh

      - name: Rename ISO
        run: |
          sudo mv images/*.iso Carlinho-Linux-amd64.iso
          sudo chown runner:runner Carlinho-Linux-amd64.iso
          sudo chmod 644 Carlinho-Linux-amd64.iso

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Carlinho-Linux-ISO
          path: Carlinho-Linux-amd64.iso
          compression-level: 0

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Carlinho-Linux-amd64.iso

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
